---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-cloud-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spring-cloud-ns
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reader
  namespace: spring-cloud-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: spring-cloud-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: spring-cloud-ns

